### PR TITLE
Fix rust Alt comments

### PR DESCRIPTION
**Pull request by ARM9**
/// are single line documentation comments.

### CODE REVIEW

**Comment by alerque** [comment]
Hey @ARM9 thanks for taking the time to contribute. You're probably right here and I'm no expert on Rust, but before I blow it away can you give me a brief explanation here? The previous contributor that set this entry up linked to [this page in the docs](https://doc.rust-lang.org/book/comments.html) that says nothing about `/* */` style block comments. What's going on here?

**Comment by alerque** [comment]
Hey @Ilphrin, any comment on this?

**Comment by ARM9** [comment]
I see, that page seems to omit multiline comments for some reason (perhaps they don't update it regularly). See https://doc.rust-lang.org/reference.html#comments

**Comment by alerque** [comment]
I can buy that. @llphrin and anybody else that prefers the docstring comment format as the alternate, you can set it up in your vimrc file like this:

```vim
let g:NERDCustomDelimiters = { 'rust': { 'left': '//', 'altLeft': '///' }
```

**Comment by Ilphrin** [comment]
Great! :) I didn't know if there is a way to manage all kind of Rust's comments, but the common syntax is cool, thanks!

**Pull request merged**
